### ISSUE TITLE
Error Installing ruby-debug-ide: Failed to build gem native extension.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [ruby-debug/ruby-debug-ide#106]
OS_VERSION: 
Windows 2012R2

RUBY_VERSION: 
2.3.0

LOCAL_GEMS:
The following illustrates that I have the dependencies met, from a GEM perspective.  This information is interesting, since the error details seem to indicate that the debase dependency isn't met, which it obviously is.

C:\Users\Administrator>gem list --local debase

*** LOCAL GEMS ***

debase (0.2.2.beta10, 0.2.1)
debase-ruby_core_source (0.9.9)

ERROR_DETAILS:
C:\Users\Administrator>gem install ruby-debug-ide -v 0.6.0 -p http://myproxy:80

WARNING:  You don't have c:\users\administrator\.gem\ruby\2.3.0\bin in your PATH
,
          gem executables will not run.
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
**ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.**

    current directory: C:/Users/Administrator/.gem/ruby/2.3.0/gems/ruby-debug-id
e-0.6.0/ext
C:/Ruby23/bin/ruby.exe mkrf_conf.rb
Installing base gem
**Unable to resolve dependency: user requested 'debase (> 0)'**
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:231:in `search_for'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:263:in `block in sort_
dependencies'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:257:in `each'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:257:in `sort_by'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:257:in `sort_dependenc
ies'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/d
elegates/specification_provider.rb:52:in `block in sort_dependencies'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/d
elegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling
'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/d
elegates/specification_provider.rb:51:in `sort_dependencies'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/r
esolution.rb:165:in `initial_state'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/r
esolution.rb:106:in `start_resolution'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/r
esolution.rb:64:in `resolve'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/r
esolver.rb:42:in `resolve'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:188:in `resolve'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:368:in `resolve'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:484:in `re
solve_dependencies'
  C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:384:in `in
stall'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/Users/Administrator/.gem/ruby/2.3.0/gems/r
uby-debug-ide-0.6.0 for inspection.
Results logged to C:/Users/Administrator/.gem/ruby/2.3.0/extensions/x86-mingw32/
2.3.0/ruby-debug-ide-0.6.0/gem_make.out

**Comment by wellington1993** [comment]
I have the same problem:

Using ruby-debug-ide 0.6.1.beta5 from https://github.com/ruby-debug/ruby-debug-ide.git (at master@da5c619)
Building native extensions.  This could take a while...

But  at Ubuntu.
I think is related to the ruby version. I'm using the latest.

@MichaelStankiewicz Did you try downgrade ruby version.
I can't do a downgrade because I already use latest new Rails features :-)

I need help to make the gem functional at my environment.

Thanks.

**Comment by MichaelStankiewicz** [comment]
@wellington1993 I've tried with both Ruby v2.4.1 (I'm running the Chef DK on my workstation) and Ruby v2.3.0.  Do you have a specific version in mind that may work?

**Comment by wellington1993** [comment]
Hi @MichaelStankiewicz,

For me only work with versions < 2.4.1 
Just not work with higher versions.

My working version of gems(Rbenv + Ruby 2.4.1 + Rails 5.0.5:
 ```
  gem 'debase'
  gem 'ruby-debug-base', :platforms => [:jruby, :ruby_18, :mingw_18]
  gem 'ruby-debug-base19x', '>= 0.11.30.pre4', :platforms => [:ruby_19, :mingw_19]
  gem 'ruby-debug-ide', '~> 0.6.0'
```

**Comment by os97673** [comment]
2.4.1 is the latest ruby release what do you mean by "higher versions"?

**Comment by wellington1993** [comment]
Hi,

@os97673 Higher including dev versions.

**Comment by os97673** [comment]
if you want to use dev-revisions you have to provide ruby headers to debase yourself.

**Comment by pddzaic** [comment]
I have the same problem with 2.4.1:

```
Updating ruby-debug-ide
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1.beta8/ext
C:/PortableApps/Ruby/2.4.1p111/bin/ruby.exe mkrf_conf.rb
Installing base gem
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/gems/debase-0.2.2.beta10/ext
C:/PortableApps/Ruby/2.4.1p111/bin/ruby.exe -r ./siteconf20170828-9424-qxgums.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/PortableApps/Ruby/2.4.1p111/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.9.9/lib/debase/ruby_core_source.rb:15:in `create_makefile_with_core'
        from extconf.rb:47:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/debase-0.2.2.beta10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/gems/debase-0.2.2.beta10 for inspection.
Results logged to C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/debase-0.2.2.beta10/gem_make.out
C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:92:in `run'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/tempfile.rb:295:in `open'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `chdir'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `synchronize'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `build_extension'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `each'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `build_extensions'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/installer.rb:752:in `build_extensions'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/installer.rb:304:in `install'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/request_set.rb:166:in `block in install'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `each'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `install'
  C:/PortableApps/Ruby/2.4.1p111/lib/ruby/2.4.0/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1.beta8 for inspection.
Results logged to C:/PortableApps/Ruby/2.4.1p111/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/ruby-debug-ide-0.6.1.beta8/gem_make.out
```

**Comment by ViugiNick** [comment]
@pddzaic, @wellington1993, @MichaelStankiewicz Is this problem still reproduce?

**Comment by Himura2la** [comment]
@ViugiNick yes
```
PS C:\Users\glago> ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
PS C:\Users\glago> gem install ruby-debug-ide
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/ext
C:/Ruby24-x64/bin/ruby.exe mkrf_conf.rb
Installing base gem
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-0.2.2/ext
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180331-6844-ewrifj.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.10.2/lib/debase/ruby_core_source.rb:14:in `create_makefile_with_core'
        from extconf.rb:48:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/debase-0.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-0.2.2 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/debase-0.2.2/gem_make.out
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:92:in `run'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  C:/Ruby24-x64/lib/ruby/2.4.0/tempfile.rb:295:in `open'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `chdir'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `synchronize'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `build_extension'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `each'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `build_extensions'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/installer.rb:764:in `build_extensions'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/installer.rb:304:in `install'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:166:in `block in install'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `each'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `install'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-debug-ide-0.6.1/gem_make.out
PS C:\Users\glago>

**Comment by athio92** [comment]
I had similar problem in Ubuntu 16.04, using Ruby version 2.3.1.
The problem was "Failed to build gem Native extension" , followed with exit message "rake failed, exit code 1".

I solved it by updating my Rake from 10.5.0 to 12.3.1. After that, I tried installing ruby-debug-ide v0.6.1, and it works fine like magic.

**Comment by Hearen** [comment]
But I just `12.3.1` and it still failed as

```
current directory: /home/hearen/.gem/ruby/2.5.0/gems/ruby-debug-ide-0.7.0.beta7/ext
/usr/bin/ruby2.5 mkrf_conf.rb
Installing base gem
Building native extensions. This could take a while...

current directory: /home/hearen/.gem/ruby/2.5.0/gems/ruby-debug-ide-0.7.0.beta7/ext
/usr/bin/ruby2.5 -rrubygems /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake RUBYARCHDIR=/home/hearen/.gem/ruby/2.5.0/extensions/x86_64-linux/2.5.0/ruby-debug-ide-0.7.0.beta7 RUBYLIBDIR=/home/hearen/.gem/ruby/2.5.0/extensions/x86_64-linux/2.5.0/ruby-debug-ide-0.7.0.beta7
/usr/bin/ruby2.5: Is a directory -- /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake (LoadError)

rake failed, exit code 1

```

**Comment by argarner** [comment]
I received the same error on Mac. Solution was to open Xcode and agree to latest terms & conditions + allow it to run through some component updates; afterwards `gem install ruby-debug-ide` worked as expected.
