### ISSUE TITLE
Not able to insatll ruby-debug-ide

### ISSUE THREAD

**Issue by kaesy** [ruby-debug/ruby-debug-ide#140]
I got this error while trying to install ruby-debug-ide gem, Please help with solutions

`Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing ruby-debug-ide:
	ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/ext
C:/Ruby25-x64/bin/ruby.exe mkrf_conf.rb
Installing base gem
Building native extensions. This could take a while...
Building native extensions. This could take a while...
ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/debase-0.2.2/ext
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180321-3212-l08wnl.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
	--with-ruby-dir
	--without-ruby-dir
	--with-ruby-include
	--without-ruby-include=${ruby-dir}/include
	--with-ruby-lib
	--without-ruby-lib=${ruby-dir}/lib
C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:590:in `try_cpp'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:1097:in `block in have_header'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
	from C:/Ruby25-x64/lib/ruby/2.5.0/mkmf.rb:1096:in `have_header'
	from extconf.rb:31:in `block in <main>'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/debase-ruby_core_source-0.10.2/lib/debase/ruby_core_source.rb:14:in `create_makefile_with_core'
	from extconf.rb:48:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/debase-0.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/debase-0.2.2 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/debase-0.2.2/gem_make.out
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:92:in `run'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/ext_conf_builder.rb:46:in `block in build'
  C:/Ruby25-x64/lib/ruby/2.5.0/tempfile.rb:295:in `open'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:163:in `chdir'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:162:in `synchronize'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:162:in `build_extension'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:198:in `each'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/ext/builder.rb:198:in `build_extensions'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/installer.rb:769:in `build_extensions'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/installer.rb:306:in `install'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/specification.rb:97:in `install'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/request_set.rb:168:in `block in install'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/request_set.rb:156:in `each'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/request_set.rb:156:in `install'
  C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/dependency_installer.rb:409:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/ruby-debug-ide-0.6.1/gem_make.out
`

**Comment by ViugiNick** [comment]
@kaesy do you have Ruby DevKit installed?

**Comment by onipirate** [comment]
same issue here, using this version 

C:\Users\Tested>ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]

devkit installed in local is  MSYS2, I was able to install several gems except this one

C:\Users\Tested>gem install ruby-debug-ide
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/e
xt
C:/Ruby24/bin/ruby.exe mkrf_conf.rb
Installing base gem
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-0.2.2/ext
C:/Ruby24/bin/ruby.exe -r ./siteconf20180327-4432-zz1p5x.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generat
e an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpo
ne'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.10.2/l
ib/debase/ruby_core_source.rb:14:in `create_makefile_with_core'
        from extconf.rb:48:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
 be found here:

  C:/Ruby24/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/debase-0.2.2/mkmf.l
og

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-0.2
.2 for inspection.
Results logged to C:/Ruby24/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/deb
ase-0.2.2/gem_make.out
C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:92:in `run'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:48:in `block in buil
d'
  C:/Ruby24/lib/ruby/2.4.0/tempfile.rb:295:in `open'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:164:in `block (2 levels) in b
uild_extension'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `chdir'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `block in build_extens
ion'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `synchronize'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `build_extension'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:201:in `block in build_extens
ions'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `each'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `build_extensions'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/installer.rb:764:in `build_extensions'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/installer.rb:304:in `install'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/request_set.rb:166:in `block in install'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `each'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `install'
  C:/Ruby24/lib/ruby/2.4.0/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

**Comment by ViugiNick** [comment]
ok, can you please try to install `debase_ruby-core-source` gem, then try one more time to install `ruby-debug-ide`

**Comment by onipirate** [comment]
issue resolved

when I used ridk install for the msys2 devkit

I only installed the base installation

so you must install the 3rd option

Install MSYS2 and MINGW development toolchain succeeded

   1 - MSYS2 base installation
   2 - MSYS2 system update
   **3 - MSYS2 and MINGW development toolchain**
