### ISSUE TITLE
webpacker compilation hangs after upgrade to RubyMine 2018.1 and ruby-debug-ide 0.7.0.beta4 

### ISSUE THREAD

**Issue by enrico** [ruby-debug/ruby-debug-ide#144]
Webpacker compilation works correctly if I launch the app not in debug mode.

When running in debug mode I see the following on the console 
```
2018-04-06 08:30:13.890022 I [83216:puma 005] [Webpacker] Rails -- Compiling…
```

and then if (after it hangs) I stop the debug session from the IDE, I see this on the console:
```
2018-04-06 08:30:13.890022 I [83216:puma 005] [Webpacker] Rails -- Compiling…
2018-04-06 08:31:17.516603 E [83216:puma 005 compiler.rb:61] [Webpacker] Rails -- Compilation failed:

Fast Debugger (ruby-debug-ide 0.7.0.beta4, debase 0.2.2, file filtering is supported) listens on 0.0.0.0:51004
(eval):6:in `exec': undefined method `close' for nil:NilClass (NoMethodError)
	from /Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/webpacker-3.4.3/lib/webpacker/webpack_runner.rb:11:in `block in run'
	from /Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/webpacker-3.4.3/lib/webpacker/webpack_runner.rb:10:in `chdir'
	from /Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/webpacker-3.4.3/lib/webpacker/webpack_runner.rb:10:in `run'
	from /Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/webpacker-3.4.3/lib/webpacker/runner.rb:6:in `run'
	from ./bin/webpack:15:in `<main>'
```

**Comment by enrico** [comment]
looks like this is a rubymine-specific issue. closing this...
