### ISSUE TITLE
Ruby Debug IDE not installing properly on Windows 10 with 2.4.4.1 ruby + devkit 64 bit

### ISSUE THREAD

**Issue by murathp** [ruby-debug/ruby-debug-ide#151]
I am seeing the following message when I install.  I tried all possible flags including proxy, --pre.
All other gems are installing fine.... but the following is always failing.

My environment is Windows 10.

I also manually installed 0.2.2 debase and the command below is NOT seeing the debase...
so I tried with or without debase present on the PC...the dependency is not being solved.
DEVKIT is installed properly with Option 3.  I also enabled DEVKIT vars....

C:\Ruby24-x64>gem install ruby-debug-ide-0.7.0.beta4.gem
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide-0.7.0.beta4.gem:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.7.0.beta4/ext
C:/Ruby24-x64/bin/ruby.exe mkrf_conf.rb
Installing base gem
Unable to resolve dependency: user requested 'debase (> 0)'
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/installer_set.rb:71:in `add_always_install'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:384:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.7.0.beta4 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-debug-ide-0.7.0.beta4/gem_make.out

Thanks for your help in advance.  BTW, I read all of the posts below and tried everything and none helped..

**Comment by JustinAddams** [comment]
Anyone else still getting this problem?
Nothing seems to work.

**Comment by valich** [comment]
Does `debase` install successfully? What happens if you install it manually beforehand?

**Comment by JustinAddams** [comment]
It failed to automatically install.
I have manually installed both v0.2.2 and the latest beta version but the ruby-debug-ide install still fails to see it.

**Comment by valich** [comment]
Could you please attach related outputs and logs, along with `gem env` and `gem list`?

**Comment by JustinAddams** [comment]
## Gem Env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.14.1
  - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby24-x64/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: H:/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: C:/Ruby24-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby24-x64/bin
  - SPEC CACHE DIRECTORY: H:/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby24-x64/lib/ruby/gems/2.4.0
     - H:/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
     - C:\Program Files (x86)\Hewlett Packard Enterprise\Content Manager\
     - C:\Program Files\Git\cmd
     - C:\Program Files\Microsoft VS Code\bin
     - C:\Program Files\PuTTY\
     - C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
     - C:\Ruby24-x64\bin
     - C:\Users\ez001745\AppData\Local\Programs\Python\Python36-32\Scripts\
     - C:\Users\ez001745\AppData\Local\Programs\Python\Python36-32\
     - C:\Users\ez001745\AppData\Local\Microsoft\WindowsApps
     -
     - C:\Program Files\Microsoft VS Code\bin

## Gem List
*** LOCAL GEMS ***

ast (2.4.0)
bigdecimal (default: 1.3.2)
coderay (1.1.2)
debase (0.2.3.beta2, 0.2.2)
debase-ruby_core_source (0.10.3)
did_you_mean (1.1.0)
eventmachine (1.2.7 x64-mingw32)
htmlentities (4.3.4)
io-console (default: 0.4.6)
jaro_winkler (1.5.1)
json (default: 2.0.4)
kramdown (1.17.0)
mini_portile2 (2.3.0)
minitest (5.10.1)
net-telnet (0.1.1)
nokogiri (1.8.4 x64-mingw32)
openssl (default: 2.0.7)
parallel (1.12.1)
parser (2.5.1.2)
power_assert (0.4.1)
powerpack (0.1.2)
psych (default: 2.2.2)
rainbow (3.0.0)
rake (12.0.0)
rdoc (default: 5.0.0)
reverse_markdown (1.1.0)
rubocop (0.58.2)
ruby-progressbar (1.10.0)
solargraph (0.25.1)
test-unit (3.2.3)
thor (0.20.0)
tilt (2.0.8)
unicode-display_width (1.4.0)
xmlrpc (0.2.1)
yard (0.9.16)

## Output when install is attempted
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/ext
C:/Ruby24-x64/bin/ruby.exe mkrf_conf.rb
Installing base gem
Unable to resolve dependency: user requested 'debase (> 0)'
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:231:in `search_for'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:263:in `block in sort_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:257:in `each'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:257:in `sort_by'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:257:in `sort_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver.rb:188:in `resolve'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:368:in `resolve'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:484:in `resolve_dependencies'
  C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:384:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-debug-ide-0.6.1/gem_make.out

**Comment by ViugiNick** [comment]
@JustinAddams @murathp Maybe updating your rake gem will help.

**Comment by ViugiNick** [comment]
@JustinAddams  @murathp Maybe https://github.com/ruby-debug/ruby-debug-ide/issues/140 will help
