### ISSUE TITLE
Debugger fails on apple m1

### ISSUE THREAD

**Issue by AnshumanTripathi** [ruby-debug/ruby-debug-ide#219]
Debugger fails to run on apple m1.

```
Traceback (most recent call last):
	7: from /Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/ruby-debug-ide-2.3.1/bin/rdebug-ide:8:in `<main>'
	6: from /Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/ruby-debug-ide-2.3.1/bin/rdebug-ide:8:in `require_relative'
	5: from /Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/ruby-debug-ide-2.3.1/lib/ruby-debug-ide.rb:9:in `<top (required)>'
	4: from /Users/anshumantripathi/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	3: from /Users/anshumantripathi/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/debase-2.3.2/lib/debase.rb:7:in `<top (required)>'
	1: from /Users/anshumantripathi/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/anshumantripathi/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/debase-2.3.2/lib/debase_internals.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/debase-2.3.2/lib/debase_internals.bundle: mach-o, but wrong architecture
	/Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/debase-2.3.2/lib/debase_internals.bundle: mach-o, but wrong architecture - /Users/anshumantripathi/.rvm/gems/ruby-2.7.3/gems/debase-2.3.2/lib/debase_internals.bundle

Process finished with exit code 1

```

## Environment
- MacOS Big Sur version 11.3.1.
- Apple M1
- IntelliJ 2021.1.2
- Ruby plugin v. 211.7442.9
- rvm version `1.29.12-next`

**Comment by AnshumanTripathi** [comment]
This solution helped https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-434619796

**Comment by AnshumanTripathi** [comment]
Updating IntelliJ to the new apple silicon compatible version fixed the problem.
