### ISSUE TITLE
Undefined method 'index' for nil:NilClass @ /usr/local/bundle/ruby/2.6.0/gems/debase-0.2.4.1/lib/debase/context.rb:35:in `at_line'

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [ruby-debug/ruby-debug-ide#222]
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/debase-0.2.4.1/lib/debase.rb:161: warning: already initialized constant Debugger
cpd-web-1     | /usr/local/bundle/gems/debase-0.2.4.1/lib/debase.rb:161: warning: previous definition of Debugger was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide.rb:10: warning: already initialized constant Debase::FRONT_END
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide.rb:10: warning: previous definition of FRONT_END was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/version.rb:2: warning: already initialized constant Debase::IDE_VERSION
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/version.rb:2: warning: previous definition of IDE_VERSION was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/command.rb:35: warning: already initialized constant Class::DEF_OPTIONS
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/command.rb:35: warning: previous definition of DEF_OPTIONS was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/commands/variables.rb:64: warning: already initialized constant Debase::VarInstanceCommand::BINDING_COMMAND
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/commands/variables.rb:64: warning: previous definition of BINDING_COMMAND was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:8: warning: already initialized constant Debase::OverflowMessageType::NIL_MESSAGE
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:8: warning: previous definition of NIL_MESSAGE was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:9: warning: already initialized constant Debase::OverflowMessageType::EXCEPTION_MESSAGE
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:9: warning: previous definition of EXCEPTION_MESSAGE was here
cpd-web-1     | /usr/local/bundle/ruby/2.6.0/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:10: warning: already initialized constant Debase::OverflowMessageType::SPECIAL_SYMBOL_MESSAGE
cpd-web-1     | /usr/local/bundle/gems/ruby-debug-ide-0.7.3/lib/ruby-debug-ide/xml_printer.rb:10: warning: previous definition of SPECIAL_SYMBOL_MESSAGE was here
cpd-web-1     | => Booting Puma
cpd-web-1     | => Rails 5.1.7 application starting in development
cpd-web-1     | => Run `rails server -h` for more startup options
cpd-web-1     | Exiting
cpd-web-1     | Uncaught exception: undefined method `index' for nil:NilClass
cpd-web-1     | 	/usr/local/bundle/ruby/2.6.0/gems/debase-0.2.4.1/lib/debase/context.rb:35:in `at_line'
cpd-web-1     | 	/data/app/controllers/application_controller.rb:7:in `<class:ApplicationController>'
cpd-web-1     | 	/data/app/controllers/application_controller.rb:3:in `<top (required)>'
cpd-web-1     | 	/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:477:in `load'
cpd-web-1     | 	/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:477:in `block in load_file

**Comment by MPLSFedResearchTZ** [comment]
dock compose file:
version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/data
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      POSTGRES_PORT: 5432
      SOLR_DEVELOPMENT_URL: http://solr:8983/solr/hydra-development
      SOLR_TEST_URL: http://solr:8983/solr/hydra-test
      FCREPO_DEVELOPMENT_URL: http://fcrepo:8080/rest/
      FCREPO_TEST_URL: http://fcrepo:8080/rest/
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && rdebug-ide --host 0.0.0.0 --port 9000 -- bin/rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - db
      - fcrepo
      - solr
      - redis
    ports:
      - 3000:3000
      - 9000:9000
      - 26162:26162

**Comment by MPLSFedResearchTZ** [comment]
I use VScode and ruby version 2.6.3.

{
            "name": "Attach to Docker",
            "type": "Ruby",
            "request": "attach",
            "remotePort": "9000",
            "remoteHost": "0.0.0.0",
            "remoteWorkspaceRoot": "/data",
            "cwd": "${workspaceRoot}",
            "showDebuggerOutput": true
        }

I had to remove/deactivate all the breakpoints to avoid this error. However, with removed/deactivated breakpoints, the debugger cannot be attached to the running code, which goes as soon as I click the debug button.
