### ISSUE TITLE
Incompatibility with ruby 3.3.0 on Sonoma?

### ISSUE THREAD

**Issue by adrianthedev** [ruby-debug/ruby-debug-ide#242]
Hey hey,

I'm hitting this error when I try to run `bundle install` with `ruby-debug-ide` gem.

This is out of my league and would love some guidance.

Thank you!

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ruby-debug-ide-0.7.3/ext
/Users/adrian/.rbenv/versions/3.3.0/bin/ruby mkrf_conf.rb
Installing base gem
Building native extensions. This could take a while...
Building native extensions. This could take a while...
ERROR: Failed to build gem native extension.

    current directory: /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/debase-0.2.5.beta2/ext
/Users/adrian/.rbenv/versions/3.3.0/bin/ruby extconf.rb
checking for vm_core.h... no
checking for vm_core.h... no
checking for vm_core.h... yes
checking for iseq.h... no
checking for iseq.h... no
Makefile creation failed
*************************************************************

  NOTE: If your headers were not found, try passing
        --with-ruby-include=PATH_TO_HEADERS

*************************************************************

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/adrian/.rbenv/versions/3.3.0/bin/$(RUBY_BASE_NAME)
	--with-ruby-dir
	--without-ruby-dir
	--with-ruby-include=${ruby-dir}/include
	--with-ruby-lib=${ruby-dir}/lib
	--without-ruby-lib
	--with-vm_core-dir
	--without-vm_core-dir
	--with-vm_core-include=${vm_core-dir}/include
	--without-vm_core-include
	--with-vm_core-lib=${vm_core-dir}/lib
	--without-vm_core-lib
	--with-iseq-dir
	--without-iseq-dir
	--with-iseq-include=${iseq-dir}/include
	--without-iseq-include
	--with-iseq-lib=${iseq-dir}/lib
	--without-iseq-lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/debase-0.2.5.beta2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/debase-0.2.5.beta2 for inspection.
Results logged to /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/debase-0.2.5.beta2/gem_make.out
/Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:330:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/resolver/specification.rb:105:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/request_set.rb:281:in `block in install_into'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/request_set.rb:273:in `each'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/request_set.rb:273:in `install_into'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/request_set.rb:148:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/dependency_installer.rb:250:in `install'
  mkrf_conf.rb:31:in `rescue in <main>'
  mkrf_conf.rb:24:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ruby-debug-ide-0.7.3 for inspection.
Results logged to /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/ruby-debug-ide-0.7.3/gem_make.out

  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/rake_builder.rb:14:in `build'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/source/rubygems.rb:200:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/worker.rb:62:in `apply_func'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in `process_queue'
  /Users/adrian/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.6/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing ruby-debug-ide (0.7.3), and Bundler cannot continue.

In Gemfile:
  ruby-debug-ide
```

**Comment by anitagraham** [comment]
Have you got the latest Xcode? I had a similar problem wiith  ` vm_core.h` which was fixed by downloading the latest Xcode

**Comment by mscrivo** [comment]
Hitting this as well, definitely latest xcode update a few days ago that caused it.

**Comment by tmorton** [comment]
I fixed this issue with the following steps:

- Make sure your `Gemfile` includes this line: `gem "debase", "0.2.5.beta2"`
- Do this setup setup before you install: `bundle config build.debase --global "--with-cflags=-Wno-error=incompatible-function-pointer-types"`

For background, see:
- [This article](https://blog.arkency.com/how-to-get-burned-by-16-years-old-hack-in-2024/) - explains how `ruby-debug-ide` uses `debase`
- https://github.com/ruby-debug/debase/issues/108 in the `debase` repo

**Comment by stanhu** [comment]
The pointer errors in `debase` look like they will be fixed by https://github.com/ruby-debug/debase/pull/110.

**Comment by pattonfu** [comment]
follow up
