### ISSUE TITLE
Debugger cannot attach to a multi-process Passenger server

### ISSUE THREAD

**Issue by toncid** [ruby-debug/ruby-debug-ide#62]
Hello,

When using Passenger as local dev server and when configured to run in multi-process mode (e.g. with `--min-instances 3 --max-pool-size 3`), the debugger is not able to attach to it.

```
App 99288 stderr: Fatal exception in DebugThread loop: Address already in use - bind(2) for "127.0.0.1" port 53437
App 99288 stderr: Backtrace:
App 99288 stderr: /Users/tonci/.rvm/gems/ruby-2.1.3/gems/ruby-debug-ide-0.4.23.beta1/lib/ruby-debug-ide.rb:108:in `initialize'
App 99288 stderr:   from: /Users/tonci/.rvm/gems/ruby-2.1.3/gems/ruby-debug-ide-0.4.23.beta1/lib/ruby-debug-ide.rb:108:in `new'
App 99288 stderr:   from: /Users/tonci/.rvm/gems/ruby-2.1.3/gems/ruby-debug-ide-0.4.23.beta1/lib/ruby-debug-ide.rb:108:in `block in start_control'
Filter chain halted as #<Proc:0x007fa055999ec0@/Users/tonci/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.6/lib/action_controller/metal/http_authentication.rb:71> rendered or redirected
App 99288 stdout: 
[ 2014-10-15 13:17:14.9334 99258/0x10a0cf000 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /Users/tonci/RubymineProjects/test-server: An error occured while starting the web application.
```

**Comment by toncid** [comment]
This issue is now resolved.
