### ISSUE TITLE
RubyMine + byebug 4.0.3 + ruby-debug-ide 0.4.28 exception

### ISSUE THREAD

**Issue by dvddmt** [ruby-debug/ruby-debug-ide#69]
So here is what I see when start debugging session in RubyMine:
```
/home/dmitry/.rvm/rubies/ruby-2.2.0/bin/ruby -e at_exit{sleep(1)};$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /home/dmitry/.rvm/gems/ruby-2.2.0/gems/ruby-debug-ide-0.4.28/bin/rdebug-ide --disable-int-handler --evaluation-timeout 10 --rubymine-protocol-extensions --port 36273 --dispatcher-port 37467 -- /home/dmitry/Disk/Programming/Ruby/tests/CodeAcademy/bin/rails server -b 127.0.0.1 -p 3000 -e development
Fast Debugger (ruby-debug-ide 0.4.28, debase 0.1.2) listens on 127.0.0.1:36273
**Uncaught exception: Could not find byebug-4.0.1 in any of the sources**
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:92:in `block in materialize'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:85:in `map!'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:85:in `materialize'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/definition.rb:132:in `specs'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/definition.rb:177:in `specs_for'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/definition.rb:166:in `requested_specs'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/environment.rb:18:in `requested_specs'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:13:in `setup'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler.rb:122:in `setup'
	/home/dmitry/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/setup.rb:18:in `<top (required)>'
	/home/dmitry/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/dmitry/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/dmitry/Disk/Programming/Ruby/tests/CodeAcademy/config/boot.rb:3:in `<top (required)>'
	/home/dmitry/Disk/Programming/Ruby/tests/CodeAcademy/bin/rails:7:in `require_relative'
	/home/dmitry/Disk/Programming/Ruby/tests/CodeAcademy/bin/rails:7:in `<top (required)>'
```

As you can see **Uncaught exception: Could not find byebug-4.0.1 in any of the sources**, but my byebug version is (4.0.3). Byebug version 4.0.1 doesn't work with RubyMine according to [this issue](https://github.com/deivid-rodriguez/byebug/issues/117) which has been fixed in byebug(4.0.3).

**Comment by os97673** [comment]
Perhaps byebug 4.0.1 is listed in your Gemfile.lock?
