### ISSUE TITLE
Exception in DebugThread loop: closed stream

### ISSUE THREAD

**Issue by sweetdub** [ruby-debug/ruby-debug-ide#75]
Hello!

I have an issue trying to launch debugger from Delayed Job. Here's debug log I have:

    /home/vagrant/.rvm/rubies/default/bin/ruby -e 'at_exit{sleep(1)};$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift)' /home/vagrant/.gem/ruby/2.2.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide --debug --disable-int-handler --evaluation-timeout 10 --rubymine-protocol-extensions --port 59470 --dispatcher-port 48268 -- /vagrant/bin/delayed_job run
    Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 127.0.0.1:59470
    Connected from 127.0.0.1
    5372: Starting control thread
    5372: Processing in control: include /vagrant/
    5372: <fileIncluded file="/vagrant/"/>
    5372: Processing in control: exclude /vagrant/tmp/
    5372: <fileExcluded file="/vagrant/tmp/"/>
    5372: Processing in control: start
    5372: Starting: running program script
    5372: INTERNAL ERROR!!! closed stream

    5372: <error>
    5372: <error>
    Fatal exception in DebugThread loop: closed stream
    Backtrace:
    /home/vagrant/.gem/ruby/2.2.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:114:in `accept'
      from: /home/vagrant/.gem/ruby/2.2.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:114:in `block in start_control'

    Process finished with exit code 2

I'm using Rubymine 8.0.3, vagrant, ruby 2.2.0 with rvm and ruby-debug-ide 0.6. I tried launch debugging with rails server and it worked. I also removed all breakpoints but it still crashed.

It's quite similar to #38 and #58 but it didn't help me to fix this issue.

Thank you guys!

**Comment by sweetdub** [comment]
I try by updating related gems :
- ruby-debug-ide 0.6.1.beta1
- debase 0.2.2.beta6
- last delayed_job 4.1.1

I tried with rake tasks and I worked but I still have this issue with delayed_job.
