### ISSUE TITLE
Unable to install Win10

### ISSUE THREAD

**Issue by lumean** [ruby-debug/ruby-debug-ide#90]
Hi,
I'm also not able to install. I tried already installing debase first, but this fails, too (already opened an issue in the debase repo). Do you have any suggestions?

```
D:\>gem install debase --pre
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.

    current directory: D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-0.2.2.beta9/ext
D:/Anwendungen/ruby/ruby225-p319/bin/ruby.exe -r ./siteconf20170202-5100-wcjmn3.rb extconf.rb

D:\Anwendungen\ruby\ruby225-p319\lib\ruby\gems\2.2.0\gems\debase-0.2.2.beta9\ext>uru 225
---> Now using ruby 2.2.5-p319 tagged as `225p319`
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Anwendungen/ruby/ruby225-p319/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.9.6/lib/debase/ruby_core_source.rb:15:in `call'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.9.6/lib/debase/ruby_core_source.rb:15:in `create_makefile_with_core'
        from extconf.rb:47:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/debase-0.2.2.beta9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-0.2.2.beta9 for inspection.
Results logged to D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/debase-0.2.2.beta9/gem_make.out
```

```
D:\>gem install ruby-debug-ide
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.6.0/ext
D:/Anwendungen/ruby/ruby225-p319/bin/ruby.exe mkrf_conf.rb

D:\Anwendungen\ruby\ruby225-p319\lib\ruby\gems\2.2.0\gems\ruby-debug-ide-0.6.0\ext>uru 225
---> Now using ruby 2.2.5-p319 tagged as `225p319`
Installing base gem
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-0.2.2.beta9/ext
D:/Anwendungen/ruby/ruby225-p319/bin/ruby.exe -r ./siteconf20170202-4776-7yyq36.rb extconf.rb

D:\Anwendungen\ruby\ruby225-p319\lib\ruby\gems\2.2.0\gems\debase-0.2.2.beta9\ext>uru 225
---> Now using ruby 2.2.5-p319 tagged as `225p319`
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Anwendungen/ruby/ruby225-p319/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.9.6/lib/debase/ruby_core_source.rb:15:in `call'
        from D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-ruby_core_source-0.9.6/lib/debase/ruby_core_source.rb:15:in `create_makefile_with_core'
        from extconf.rb:47:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/debase-0.2.2.beta9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/debase-0.2.2.beta9 for inspection.
Results logged to D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/debase-0.2.2.beta9/gem_make.out
D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:92:in `run'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/2.2.0/tempfile.rb:319:in `open'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `chdir'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:162:in `synchronize'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:162:in `build_extension'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `each'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `build_extensions'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:752:in `build_extensions'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:304:in `install'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
  D:/Anwendungen/ruby/ruby225-p319/lib/ruby/site_ruby/2.2.0/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.6.0 for inspection.
Results logged to D:/Anwendungen/ruby/ruby225-p319/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/ruby-debug-ide-0.6.0/gem_make.out

D:\>

D:\>gem --version
2.6.10

```

**Comment by denofevil** [comment]
@lumean thank you for the report, let's keep in in debase
