### ISSUE TITLE
Missing dependency on debase in Gemspec

### ISSUE THREAD

**Issue by proteantech** [ruby-debug/ruby-debug-ide#92]
I believe there should be a dependency on debase in the gemspec. I get an error when trying to run "rdebug-ide" saying 

LoadError: cannot load such file -- debase
  /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:8:in `require'

While this can be resolved by simply installing the gem, it should not be necessary after I have added the "ruby-debug-ide" gem to my Gemfile and did a bundle install. Any dependencies for this gem should be pulled in on install, but since the dependency is not listed in the Gemfile, it needs to be done manually.

**Comment by denofevil** [comment]
No, there should be no dependency on debase. Its installation is handled by https://github.com/ruby-debug/ruby-debug-ide/blob/master/ext/mkrf_conf.rb because there's no way to tell rubygems to install different gems for different ruby versions.
Usually this error appears when debase is installed and ruby was updated after that. If it's not the case we'd love to get some repro scenario

**Comment by vpithart** [comment]
Same here. When `bundle exec rdebug-ide ./test_bench/bench.rb`, it fails:

```
bundler: failed to load command: rdebug-ide (/Users/vpithart/.rbenv/versions/2.4.3/bin/rdebug-ide)
LoadError: cannot load such file -- debase
  /Users/vpithart/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:10:in `require'
  /Users/vpithart/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:10:in `<top (required)>'
  /Users/vpithart/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:8:in `require_relative'
  /Users/vpithart/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:8:in `<top (required)>'
  /Users/vpithart/.rbenv/versions/2.4.3/bin/rdebug-ide:23:in `load'
  /Users/vpithart/.rbenv/versions/2.4.3/bin/rdebug-ide:23:in `<top (required)>'
```

Fresh installation of `ruby 2.4.3` through `rbenv`, then `bundle install`. 

The `debase-2.2.0` is present in my `~/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems`.

**Comment by victorsosa** [comment]
Having similar issue:

```
[vns@betito perseus]$ rake routes
rake aborted!
LoadError: cannot load such file -- debase
/usr/local/share/gems/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:9:in `require'
/usr/local/share/gems/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:9:in `<top (required)>'
/usr/local/share/gems/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `require'
```
Just try to run  `rake routes` in a project with ruby-debug-ide

**Comment by victorsosa** [comment]
This is how to fix this issue:

```
group :development, :test do
    gem 'ruby-debug-ide'
    gem 'debase'
end
```

**Comment by cooperka** [comment]
Fixed by manually removing all references to `debase` from my ruby installation (simply uninstalling debase didn't work for me, things got left behind causing this error). For example, remove all files matching:

```bash
ls ~/.rbenv/versions/2.4.3/**/debase*
```

Then simply `gem install debase` and it worked for me.

**Comment by themichaelolson** [comment]
Ensuring 'ruby-debug-ide' is installed before 'debase' appears to work for me, however there exists a race condition when `bundle install --jobs` is >1. Could use a more extensible solution.

Additional details:
Ruby 3.0.2
Bundler 2.2.22
ruby-debug-ide 0.7.3 (latest)
debase >=0.2.5.beta2

**Comment by emmahyde** [comment]
@themichaelolson absolutely right, I was running multiple `bundle --jobs`!
```ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
Bundler version 2.3.7
ruby-debug-ide (0.7.3)
debase (0.2.5.beta2)
debase-ruby_core_source (0.10.15)```
